calibration = calibrateRadarNoise('./data/dataset.h5', ...
    'Runs', {'2_23_2021_edgar_classroom_run4'}, ...   % <- was 'edgar_army_run5'
    'FrameStride', 1, ...
    'OutFile', 'radar_noise_calibration.json');